# Make file for cargo make
[tasks.build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--profile", "wasm"]

[tasks.pkg]
command = "bash"
args = ["./pkg.sh"]

[tasks.all]
dependencies = ["build", "pkg"]